### ISSUE TITLE
Set Up Server Infrastructure with Google Firebase

### ISSUE THREAD

**Issue by brendanpayne** [brendanpayne/protifyapp#12]
### Story Description:
Establish the server infrastructure using Google Firebase for the application.

#### Acceptance Criteria:

1. Create a new Firebase project.
   - Set up a Firebase project with appropriate configurations.

2. Set up Firebase Authentication.
   - Implement user authentication using Firebase Authentication to manage user accounts.
   - This will be used in https://github.com/brendanpayne/protifyapp/milestone/2

3. Configure Firebase Firestore as the database.
   - Set up Firestore to store user accounts and events.

4. Implement necessary security rules.
   - Define security rules to ensure data integrity and protect against unauthorized access.

#### Additional Information:

- Ensure that Firebase configurations and credentials are securely stored and managed.
- Utilize Firebase documentation and best practices for effective setup and security.

#### Tasks:

- [x] Create a new Firebase project and configure it.
- [x] Set up Firebase Authentication for user management.
- [x] Configure Firestore as the database for user accounts and events.
- [x] Implement security rules to protect data.

#### Definition of Done:

- A Firebase project is created and properly configured.
- User authentication is implemented and validated.
- Firestore is set up and functional for storing user accounts and events.
- Security rules are defined and tested for data protection.

**Comment by uc-mcreyntm** [comment]
I created a firebase account and added necessary configurations to the project to interact with firebase. I added in some test code for a user to create a username and password using email/pass authentication. I still need to implement it into the front end for testing

**Comment by uc-mcreyntm** [comment]
Authentication branch now has a working implementation of firebase. I was able to create a user using the login page and it was successfully added to the firebase console.

**Comment by uc-mcreyntm** [comment]
I added a nav controller that allows users to use a login or register page. I added functionality to the login page so users are able to log in, then be redirected to a "home" page that will display their email address. I just used the email address in this instance, but I have a lot of other data I could use, such as last login date and uid. From here, I am going to work on making a firestore database to allow users to store data (which will eventually be in the form of calendar events), and have it displayed on a home page of sorts.

**Comment by uc-mcreyntm** [comment]
Successfully implemented firestore into the application. It checks to see if there is a document in the collection if the UID of the currently signed in user. If it doesn't exist, then it will create it and also add in the timestamp that the user's account was created.

![Image](https://github.com/brendanpayne/protifyapp/assets/89491042/15a684e7-387a-4f5a-a8a5-fa6dfb7ba2c1)

**Comment by uc-mcreyntm** [comment]
Set up basic event storing for users in Firestore. Last step is to implement security measures. I will talk to Cole about this



![Image](https://github.com/brendanpayne/protifyapp/assets/89491042/bcf5f4f5-8556-412a-b10b-a7d3886fc3a8)
