### ISSUE TITLE
Create Unit Tests for Firebase Auth

### ISSUE THREAD

**Issue by brendanpayne** [brendanpayne/protifyapp#17]
### Story Description:
Unit tests will need to created to test firebase auth functionality is working as intended. 

#### Acceptance Criteria:

1. Create unit tests for firebase auth.
   - Confirm login unit test
   - Event storing and receiving unit test
   - Successful user registration unit test

2. Newly created tests pass.

#### Additional Information:

- Unit tests should be structured similarly to the layout of the project.
  - i.e. app.features.login.loginActivity -> tests.features.login.loginTests

#### Tasks:

- [x] Created the confirm login test.
- [x] Created the event storing and receiving test.
- [x] Created user registration test.
- [x] All tests pass.

#### Definition of Done:

- All tests are created and are passing.

**Comment by uc-mcreyntm** [comment]
Trying to troubleshoot unit tests not running successfully 

![Image](https://github.com/brendanpayne/protifyapp/assets/89491042/e82743d9-4a35-457f-9180-2d632cff7343)

**Comment by uc-mcreyntm** [comment]
Trying to troubleshoot issues with the unit tests failing

**Comment by uc-mcreyntm** [comment]
Moving to another story

**Comment by uc-mcreyntm** [comment]
Created unit test that creates a user account, logs in, creates an event, and retreives the event with set up and destruction are implemented
Unit test passing.
