### ISSUE TITLE
Create Month View for Calendar

### ISSUE THREAD

**Issue by brendanpayne** [brendanpayne/protifyapp#20]
### Story Description:
Create a view to show a full month rather than just a week within the calendar component.

#### Acceptance Criteria:

1. Create Monthly View
   - Display a grid representing days in the month.

2. Create a button or clickable element to toggle month view 
   - Toggles between weekly and monthly view.

#### Additional Information:

- Possibly change the way views display days of week/month
   - Maybe a label for weeks/month?

#### Tasks:

- [x] Create a monthly view
- [x] Create a toggle between monthly/weekly view
- [ ] Ensure the calendar view functions normally

#### Definition of Done:

- Calendar can show monthly view.
- Calendar can toggle between views.
- Homepage layout still functions normally.

**Comment by brendanpayne** [comment]
Tyler and I made some progress on the month view with help from our best friend co-pilot, and got a "functional" month view working. Things will need to be tweaked over the course of this sprint but hopefully we can get it all ironed out before next sprint planning/discussion meeting.
