### ISSUE TITLE
Connect Google Maps API

### ISSUE THREAD

**Issue by kramerc3** [brendanpayne/protifyapp#25]
### Story Description:
This will serve as the initial integration of traffic data in Protify.

#### Acceptance Criteria:
1. API added to build file

2. Location data variable passed to function

3. Test calls can be executed

#### Additional Information:
- TBD

#### Tasks:
- [x] Register & Test API Key
- [x] Store API Key in Environment Variable
- [x] Pass location data variable
- [x] Create a function for finding the estimated travel time between location and destination
- [x] Any traffic concerns (if possible)
- [ ] Create basic logic for testing API calls

**Comment by uc-mcreyntm** [comment]
Successfully connected maps API. Working on implementing into app. It looks like it has all of the features that we are going to want for our app (like departure time).

**Comment by uc-mcreyntm** [comment]
Implemented a functional prototype of the distance matrix api (Google Maps API). In this example, it uses the users current location as the starting location, and a preset destination (Brooklyn NY). The departure time is set for 1 day in the future. From this it makes the request to the api and gets the amount of time it will take in seconds to get there (with traffic estimation included).

https://github.com/brendanpayne/protifyapp/assets/89491042/28ead12a-6948-46c0-9b89-14aa84f962e7

**Comment by uc-mcreyntm** [comment]
Looking to implement the Route API so I can add in a stop along the way to calulate any potential time savings.

Example: Going to the gym on the way home from work only adds 4 minutes to your travel time, where if you were to go to the gym from your house, it would be 20 minute drive.

**Comment by uc-mcreyntm** [comment]
Routes API is partially implemented. You can add "waypoints" to your destination and it will output the total time that it will take. We can use this in the AI model to determine the best way to save time when driving

**Comment by uc-mcreyntm** [comment]
Started working on efficiently chaining events to save driving time. In this example, you can see that it will take 607 seconds times two (because you have to drive there, and then back home). If you were to add that same stop on the way home from work, it would only add 234 additional seconds. Making for a time savings of about 900 seconds. This is over the 600 seconds threshold, so in this case, it would make a proposal to change the event time.


![Image](https://github.com/brendanpayne/protifyapp/assets/89491042/6230d95f-e43b-4a0b-875e-de2e362eeaed)

**Comment by uc-mcreyntm** [comment]
Made a new class for the distance matrix API to get rid of the duplicates, for example, the old output would look like this

location 1 to location 2 takes 43 minutes
location 2 to location 1 takes 35 minutes.

Although these are accurate (for example, going into columbus at 5pm vs leaving columbus at 5pm will give you some very different travel times), it seemed to confuse the AI. I might come back to this to see if GPT 4 can handle it, but it's on the backburner for now.

**Comment by uc-mcreyntm** [comment]
Created function to geocode events. The weather AI only takes longitude and lattitude, so a string won't cut it. This class takes that string and gets the longitude and lattitude for that location, which in turn can be used for the weather API.
