### ISSUE TITLE
UI/UX Improvements

### ISSUE THREAD

**Issue by brendanpayne** [brendanpayne/protifyapp#72]
### Story Description:
As a **Protify user** I want to **have more clear indicators within various parts of the app** so that **my experience is more refined and easier to comprehend.**

#### Acceptance Criteria:

1. Add icon for events that are unoptimizable.
   - "Lock" icon indicating that the current event can not be optimized.
   - Include in breakdown view and event details page.

2. Improvements to Month View
   - Add an extra week to month if month spans more than 5 weeks.
   - Visual indication on what days are apart of month and what days are apart of the previous/next.
   - Update header to appropriate month name when scrolling through month/week view. 

3. Pass selected date to Add Event page.
   - Fill date field with selected date rather than today's date.
 
4. Click and hold on empty timeslot to add event.
   - Add the ability to add an event by clicking on an empty space on the breakdown
   - Pass the time between the dividers as the start and end times as well as current date.

#### Additional Information:

There are probably other improvements that can be done to the UI but these are the only ones that I can think of when thinking back to the feedback from expo.

#### Tasks:

- [x] Lock Icon added to Event Breakdown
- [x] Lock Icon added to Event Details
- [x] Extra week logic for Month view
- [x] Grayed out dates for previous/next months in Month view
- [ ] Improved header to better indicate current month
- [x] Selected date passed through to Add Event page
- [x] Add event via click & hold on empty time slot.

#### Definition of Done:

- Indicator for "locked" events on Breakdown and Event Details page.
- Month view improvements are implemented.
- Selected date passed through to Add Event page
- Events can be added via long click on empty time slot.

**Comment by brendanpayne** [comment]
A look at the month view with grayed out dates, as well as lock icons on events that can not be optimized.

![Image](https://github.com/brendanpayne/protifyapp/assets/75294679/e47a96eb-adba-460b-b234-db2a2f3f0f0c)
